### ISSUE TITLE
Could not install via cocoapods.

### ISSUE THREAD

**Issue by 0x0c** [satoshin2071/SwiftyVerticalScrollBar#1]
Hi,

I'm trying to install this library to my project via cocoapods but I can't.

I'm using cocoapods 1.0.0 and when I run `pod install` the install sequence is stopped with the following error message.

```
[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `SwiftyVerticalScrollBar_Example`..
```

How to fix this issue?

**Comment by 0x0c** [comment]
すみません日本語で大丈夫です

**Comment by satoshin2071** [comment]
Podfileで明示的にTargetを指定すれば問題なくインストールできるみたいです👀

``` Ruby
platform :ios, '8.0'
use_frameworks!

target 'Example' do
  pod 'SwiftyVerticalScrollBar'
end
```

**Comment by 0x0c** [comment]
おｋですやってみますー！
